all: cc0pi_analyzer univmake

univmake: univmake.C
	$(CXX) $(shell root-config --cflags --libs) -O3 -o $@ $^

cc0pi_analyzer: cc0pi_analyzer.C
	$(CXX) $(shell root-config --cflags --libs) -O3 -o $@ $^

.PHONY: clean

clean:
	$(RM) univmake cc0pi_analyzer
